config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }

  resources :categories,  only: :show
  resources :order_items, except: [:new, :show, :edit]

  resource :customer, only: :edit do
    collection do
      patch :update_address
      patch :update_password
      patch :update_email
    end
  end

  resources :books, only: [:index, :show]  do
    resources :ratings, only: [:new, :create]
  end

  resources :orders, only: [:index, :show] do
    member do
      get    :complete
      patch  :add_discount
    end
    delete :clear_cart, on: :collection
  end

  namespace :checkouts do
    get   :edit_address
    patch :update_address

    get   :choose_delivery
    patch :set_delivery

    get   :confirm_payment
    patch :update_credit_card

    get   :overview
    get   :confirmation
  end

  root 'home#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :orders, dependent: :nullify
  has_many :ratings, dependent: :destroy
  belongs_to :billing_address, class_name: "Address", dependent: :destroy
  belongs_to :shipping_address, class_name: "Address", dependent: :destroy

  validates :email, :encrypted_password, presence: true

  after_create :create_address

  accepts_nested_attributes_for :billing_address
  accepts_nested_attributes_for :shipping_address


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0,20]
    end
  end
  
  private
  def create_address
    self.build_billing_address
    self.build_shipping_address
    self.save
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @customer = Customer.from_omniauth(request.env["omniauth.auth"])
    if @customer.persisted?
      sign_in_and_redirect @customer, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_customer_registration_url
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  load_and_authorize_resource
  before_action :current_order, only: :edit

  def edit
    @billing_address = current_user.billing_address
    @shipping_address = current_user.shipping_address
  end

  def update_address
    if params[:billing_address]
      current_user.billing_address.update(billing_params)
    elsif params[:shipping_address]
      current_user.shipping_address.update(shipping_params)
    end
    redirect_to edit_customer_path
  end

  def update_password
    @customer = Customer.find(current_user.id)
    if @customer.update_with_password(customer_params)
      sign_in @customer, :bypass => true
      redirect_to root_path
    else
      redirect_to edit_customer_path
    end
  end

  def update_email
    current_user.update(customer_params)
    redirect_to edit_customer_path
  end

  private
  def billing_params
    params.require(:billing_address).permit(:firstname, :lastname, :street_address, :city, :country, :zipcode, :phone, :id)
  end

  def shipping_params
    params.require(:shipping_address).permit(:firstname, :lastname, :street_address, :city, :country, :zipcode, :phone, :id)
  end

  def customer_params
    params.require(:customer).permit(:current_password, :password, :email)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.haml
.container
  = render "home/header"

  .settings
    %h2= t('.settings')
    .billing_address_settings
      %h3{class: 'address_column_title'}= t('.bill_addr')
      = simple_form_for :billing_address, url: update_address_customer_path, method: :patch do |f|
        = f.input :firstname, label: false, placeholder: 'First name', input_html: {class: 'input_form'}
        = f.input :lastname, label: false, placeholder: 'Last name', input_html: {class: 'input_form'}
        = f.input :street_address, label: false, placeholder: 'Street address', input_html: {class: 'input_form'}
        = f.input :city, label: false, placeholder: 'City', input_html: {class: 'input_form'}
        = f.country_select("country", { include_blank: 'Country' }, {class: 'input_form'})
        = f.input :zipcode, as: :integer, label: false, placeholder: 'Zipcode', input_html: {class: 'input_form'}
        = f.input :phone, as: :integer, label: false, placeholder: 'Phone number', input_html: {class: 'input_form'}
        = f.submit t('.submit'), class: "save_settings btn btn-primary"
    .shipping_address_settings
      %h3{class: 'address_column_title'}= t('.shipp_addr')
      = simple_form_for :shipping_address, url: update_address_customer_path, method: :patch do |f|
        = f.input :firstname, label: false, placeholder: 'First name', input_html: {class: 'input_form'}
        = f.input :lastname, label: false, placeholder: 'Last name', input_html: {class: 'input_form'}
        = f.input :street_address, label: false, placeholder: 'Street address', input_html: {class: 'input_form'}
        = f.input :city, label: false, placeholder: 'City', input_html: {class: 'input_form'}
        = f.country_select("country", { include_blank: 'Country' }, {class: 'input_form'})
        = f.input :zipcode, as: :integer, label: false, placeholder: 'Zipcode', input_html: {class: 'input_form'}
        = f.input :phone, as: :integer, label: false, placeholder: 'Phone number', input_html: {class: 'input_form'}
        = f.submit t('.submit'), class: "save_settings btn btn-primary"
    .email_settings
      %h3{class: 'address_column_title'}= t('.email')
      = form_for current_user, url: update_email_customer_path, method: :patch   do |f|
        = f.email_field :email, class: 'input_form'
        = f.submit t('.submit'), class: "save_settings btn btn-primary"
    .password_settings
      %h3{class: 'address_column_title'}= t('.passwrd')
      - unless current_user.provider
        = form_for current_user, url: update_password_customer_path, method: :patch, html: {class: 'update_password'}  do |f|
          = f.label :old_password
          = f.password_field :current_password, autocomplete: "off", placeholder: 'Type old password', class: 'input_form'
          = f.label :new_password
          = f.password_field :password, autocomplete: "off", placeholder: 'Type new password', class: 'input_form'
          = f.submit t('.submit'), class: "save_settings btn btn-primary"
    .remove_account
      %h3{class: 'address_column_title'}= t('.rmv_account_title')
      .form_for_remove_account
        = button_to t('.btn_rmv_account'), registration_path(current_user), method: :delete, class: 'button_remove_account btn btn-primary'
        = check_box_tag :confirm_remove_account
        = label_tag :confirm_remove_account, t('.checkbox_confirm_btn_rmv')