config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }

  resources :categories,  only: :show
  resources :order_items, except: [:new, :show, :edit]

  resource :customer, only: :edit do
    collection do
      patch :update_address
      patch :update_password
      patch :update_email
    end
  end

  resources :books, only: [:index, :show]  do
    resources :ratings, only: [:new, :create]
  end

  resources :orders, only: [:index, :show] do
    member do
      get    :complete
      patch  :add_discount
    end
    delete :clear_cart, on: :collection
  end

  namespace :checkouts do
    get   :edit_address
    patch :update_address

    get   :choose_delivery
    patch :set_delivery

    get   :confirm_payment
    patch :update_credit_card

    get   :overview
    get   :confirmation
  end

  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, current_order = nil)
    user ||= Customer.new
    if user.admin
      can :manage, :all
    else
      if user.id
        can [:new, :create], Rating, customer_id: user.id
        can [:index, :show, :complete], Order, customer_id: user.id
        can [:edit, :update_address, :update_password, :update_email], Customer, id: user.id
      end
      can :read, Book
      can :show, Category
      can [:add_discount, :clear_cart], Order, id: current_order.id if current_order
      can :create, OrderItem
      can [:index, :update, :destroy], OrderItem, order_id: current_order.id if current_order
      can :read, Rating, check: true
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :firstname, :lastname, :street_address, :city, :country, :zipcode, :phone, presence: true, on: :update
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  
  validates :firstname, :lastname, presence: true
end

app/models/billing_address.rb
class BillingAddress < Address
  has_one :customer
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  has_many   :ratings
  has_many   :order_items

  validates :title, :price, :stock_qty, presence: true

  mount_uploader :image, ImageUploader

  def self.bestsellers
    joins(order_items: :order)
    .where(orders: {state: ['in_queue','in_delivery','delivered']})
    .select('books.id, books.price, books.image, books.description, books.title,
            books.stock_qty, books.author_id, SUM(order_items.quantity) as quantity')
    .group('books.id').order('quantity DESC').limit(3)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
  
  validates :title, presence: true, uniqueness: true

  scope :has_book, -> { joins(:books).distinct.order(:id) }
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  has_many   :orders
  
  validates :number, :expiration_month, :expiration_year, :cvv, presence: true, on: :update
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :orders, dependent: :nullify
  has_many :ratings, dependent: :destroy
  belongs_to :billing_address, class_name: "Address", dependent: :destroy
  belongs_to :shipping_address, class_name: "Address", dependent: :destroy

  validates :email, :encrypted_password, presence: true

  after_create :create_address

  accepts_nested_attributes_for :billing_address
  accepts_nested_attributes_for :shipping_address


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |customer|
      customer.email = auth.info.email
      customer.password = Devise.friendly_token[0,20]
    end
  end
  
  private
  def create_address
    self.build_billing_address
    self.build_shipping_address
    self.save
  end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  has_many :orders

  validates :price, :title, presence: true

  default_scope { order("id") }
end

app/models/discount.rb
class Discount < ActiveRecord::Base
  before_create :create_code
  has_many :orders
  validates :amount, presence: true

  private
  def create_code
    self.code = rand(100000..999999)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  belongs_to :customer
  belongs_to :delivery
  belongs_to :discount,    dependent: :destroy
  belongs_to :credit_card, dependent: :destroy
  has_many   :order_items, dependent: :destroy
  
  after_create :create_credit_card

  accepts_nested_attributes_for :credit_card

  aasm column: :state do
    state :in_progress, initial: true
    state :in_queue
    state :in_delivery
    state :delivered
    state :canceled

    event :in_queue do
      transitions from: :in_progress, to: :in_queue
    end

    event :in_delivery do
      transitions from: :in_queue, to: :in_delivery
    end

    event :delivered do
      transitions from: :in_delivery, to: :delivered
    end

    event :canceled do
      transitions from: [:in_progress, :in_queue], to: :canceled
    end
  end

  def state_enum
    ['in_queue', 'in_delivery', 'delivered', 'canceled']
  end

  def items_price
    self.order_items.sum(:price)
  end

  def items_quantity
    self.order_items.sum(:quantity)
  end

  def add_book(book_id, qty)
    if order_item = self.order_items.find_by(book_id: book_id)
      order_item.quantity += qty
      order_item.price += order_item.book.price * qty
    else
      order_item = self.order_items.new(book_id: book_id, quantity: qty)
      order_item.price = order_item.book.price * qty
    end
    order_item.save
  end

  def add_discount(coupon)
    if coupon.new_state && self.discount.nil?
      coupon.update(new_state: false)
      self.discount = coupon
      self.save
    end
  end

  def set_total_price
    if self.discount
      self.total_price = self.items_price + self.delivery.price - self.discount.amount
    else
      self.total_price = self.items_price + self.delivery.price
    end
    self.save
  end

  def confirm(current_user)
    self.customer_id = current_user.id
    self.in_queue
    self.completed_date = 3.days.from_now
    self.save
  end

  private
  def create_credit_card
    self.build_credit_card
    self.save
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :order

  validates :quantity, :book_id, presence: true

  default_scope { order("id") }

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :customer
  belongs_to :book
  
  validates :rating, :title, :review, :customer_id, presence: true
end

app/models/shipping_address.rb
class ShippingAddress < Address
  has_one :customer
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource
  before_action :current_order, only: [:index, :show]
  before_action :assign_order_to_user, only: :index

  def index
    orders = current_user.orders.accessible_by(current_ability)
    @orders_in_progress = orders.in_progress
    @orders_in_queue = orders.in_queue
    @orders_in_delivery = orders.in_delivery
    @orders_delivered = orders.delivered
  end

  def show
  end

  def complete
    @credit_card = @order.credit_card
    @billing_address = current_user.billing_address
    @shipping_address = current_user.shipping_address
  end

  def add_discount
    coupon = Discount.find_by(discount_params)
    @order.add_discount(coupon) if coupon
    redirect_to :back
  end

  def clear_cart
    @order.order_items.destroy_all
    redirect_to order_items_path
  end

  private
  def discount_params
    params.require(:discount).permit(:code)
  end

  def assign_order_to_user
    if current_order
      current_user.orders << current_order
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/orders/complete.html.haml
.container
  = render "order_items/header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'} #{t('.order_number')} #{@order.id}
    .confirm_block
      %h3= t('.confirm')
      .billing_info_block
        %h4= t('.bill_addr')
        %p #{@billing_address.firstname} #{@billing_address.lastname}
        %p #{@billing_address.street_address}
        %p #{@billing_address.city} #{@billing_address.zipcode}
        %p #{@billing_address.country}
        %p #{t('.phone')} #{@billing_address.phone}
      .shipping_info_block
        %h4= t('.shipp_addr')
        %p #{@shipping_address.firstname} #{@shipping_address.lastname}
        %p #{@shipping_address.street_address}
        %p #{@shipping_address.city} #{@shipping_address.zipcode}
        %p #{@shipping_address.country}
        %p #{t('.phone')} #{@shipping_address.phone}
      .delivery_info_block
        %h4= t('.shipments')
        %p= @order.delivery.title
      .credit_card_info_block
        %h4= t('.payment_info')
        %p #{t('.stars')} #{@order.credit_card.number.last(4)}
        %p #{@order.credit_card.expiration_month}#{t('.slash')}#{@order.credit_card.expiration_year}
    .order_items_confirm
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @order.order_items.each do |order_item|
        .order_item{id: order_item.id}
          %image{src: order_item.book.image, class: "book_ico"}
          .block_title_description
            %h4= order_item.book.title
            %p= order_item.book.description
          .block_info_item
            %h4{class: "book_price"}= number_to_currency(order_item.book.price)
            %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
            %h4{class: "total_book_price"}= number_to_currency(order_item.price)
    .order_price_info_confirm
      %h5 #{t('.subtotal')} #{number_to_currency(@order.order_items.sum(:price))}
      %h5 #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5 #{t('.discount')} #{number_to_currency(@order.discount.amount)}
    .order_total_price_info_confirm
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}
    .go_back_store
      = button_to t('.go_store'), books_path, method: :get, class: 'btn btn-primary'

app/views/orders/edit.html.haml
.container
  = render "credit_cards/header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'}= t('.checkout')
      = link_to t('.address'), edit_address_path, class: 'link_address_title'
      = link_to t('.delivery'), deliveries_path, class: 'link_address_title'
      = link_to t('.payment'), edit_credit_card_path, class: 'link_address_title'
      %h4{class: 'confirm_title'}= t('.confirm')
      %h4{class: 'complete_title'}= t('.complete')
    .confirm_block
      %h3= t('.confirm')
      .billing_info_block
        %h4
          #{t('.bill_addr')}
          = link_to t('.edit'), edit_address_path
        %p #{@billing_address.firstname} #{@billing_address.lastname}
        %p #{@billing_address.street_address}
        %p #{@billing_address.city} #{@billing_address.zipcode}
        %p #{@billing_address.country}
        %p #{t('.phone')} #{@billing_address.phone}
      .shipping_info_block
        %h4
          #{t('.shipp_addr')}
          = link_to t('.edit'), edit_address_path
        %p #{@shipping_address.firstname} #{@shipping_address.lastname}
        %p #{@shipping_address.street_address}
        %p #{@shipping_address.city} #{@shipping_address.zipcode}
        %p #{@shipping_address.country}
        %p #{t('.phone')} #{@shipping_address.phone}
      .delivery_info_block
        %h4
          #{t('.shipments')}
          = link_to t('.edit'), deliveries_path
        %p #{@order.delivery.title}
      .credit_card_info_block
        %h4
          #{t('.payment_info')}
          = link_to t('.edit'), edit_credit_card_path(@order.credit_card.id)
        %p #{t('.stars')} #{@order.credit_card.number.last(4)}
        %p #{@order.credit_card.expiration_month}#{t('.slash')}#{@order.credit_card.expiration_year}
    .order_items_confirm
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @order.order_items.each do |order_item|
        .order_item{id: order_item.id}
          %image{src: order_item.book.image, class: "book_ico"}
          .block_title_description
            %h4= order_item.book.title
            %p= order_item.book.description
          .block_info_item
            %h4{class: "book_price"}= number_to_currency(order_item.book.price)
            %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
            %h4{class: "total_book_price"}= number_to_currency(order_item.total_price)
    .order_price_info_confirm
      %h5 #{t('.subtotal')} #{number_to_currency(@order_items_price)}
      %h5 #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5 #{t('.discount')} #{number_to_currency(@order.discount.amount)}
    .order_total_price_info_confirm
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}
  
    = button_to t('.place_order'), confirmation_order_path(@order), method: :get, class: 'place_order btn btn-primary'

app/views/orders/index.html.haml
.container
  = render 'home/header'

  .orders_list
    %h2= t('.orders')
    .order_in_progress
      %h3{class: 'status_title'}= t('.in_progress')
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @orders_in_progress.each do |order|
        .order_item_line{id: order.id}
          - order.order_items.each do |order_item|
            .book{id: order_item.book.id}
              .book_ico
                %image{src: order_item.book.image, class: "book_ico_orders"}
              .book_title_and_description
                %h4= order_item.book.title
                %p{class: 'book_description_orders'}= order_item.book.description
              .book_price_qty_total_price
                %h4{class: "book_price"}= number_to_currency(order_item.book.price)
                %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
                %h4{class: "total_book_price"}= number_to_currency(order_item.price)
          .subtotal_price_info_index
            %p{class: 'subtotal_price_index'} #{t('.subtotal')} #{number_to_currency(@order_items_price)}
          - if order.discount
            %p{class: 'discount_order_index'} #{t('.discount')} #{number_to_currency(order.discount.amount)}
    .orders_in_queue
      %h3{class: 'status_title'}= t('.in_queue')
      .name_columns
        %h5{class: "number_column"}= t('.number')
        %h5{class: "complete_column"}= t('.completed_at')
        %h5{class: "total_column"}= t('.total_column')
      - @orders_in_queue.each do |order|
        .order_line{id: order.id}
          .order_number
            = link_to "#{t('.order_number')}#{order.id}", order_path(order.id)
          .order_complete_date
            %h5= order.completed_date
          .order_price
            %h5= number_to_currency(order.total_price)
          .order_view_link
            = link_to t('.view_link'), order_path(order.id)
    .orders_in_delivery
      %h3{class: 'status_title'}= t('.in_delivery')
      .name_columns
        %h5{class: "number_column"}= t('.number')
        %h5{class: "complete_column"}= t('.completed_at')
        %h5{class: "total_column"}= t('.total_column')
      - @orders_in_delivery.each do |order|
        .order_line{id: order.id}
          .order_number
            = link_to "#{t('.order_number')}#{order.id}", order_path(order.id)
          .order_complete_date
            %h5= order.completed_date
          .order_price
            %h5= number_to_currency(order.total_price)
          .order_view_link
            = link_to t('.view_link'), order_path(order.id)
    .orders_delivered
      %h3{class: 'status_title'}= t('.delivered')
      .name_columns
        %h5{class: "number_column"}= t('.number')
        %h5{class: "complete_column"}= t('.completed_at')
        %h5{class: "total_column"}= t('.total_column')
      - @orders_delivered.each do |order|
        .order_line{id: order.id}
          .order_number
            = link_to "#{t('.order_number')}#{order.id}", order_path(order.id)
          .order_complete_date
            %h5= order.completed_date
          .order_price
            %h5= number_to_currency(order.total_price)
          .order_view_link
            = link_to t('.view_link'), order_path(order.id)

app/views/orders/overview.html.haml
.container
  = render "order_items/header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'} #{t('.order_number')} #{@order.id}
    .confirm_block
      %h3= t('.confirm')
      .billing_info_block
        %h4= t('.bill_addr')
        %p #{@billing_address.firstname} #{@billing_address.lastname}
        %p #{@billing_address.street_address}
        %p #{@billing_address.city} #{@billing_address.zipcode}
        %p #{@billing_address.country}
        %p #{t('.phone')} #{@billing_address.phone}
      .shipping_info_block
        %h4= t('.shipp_addr')
        %p #{@shipping_address.firstname} #{@shipping_address.lastname}
        %p #{@shipping_address.street_address}
        %p #{@shipping_address.city} #{@shipping_address.zipcode}
        %p #{@shipping_address.country}
        %p #{t('.phone')} #{@shipping_address.phone}
      .delivery_info_block
        %h4= t('.shipments')
        %p= @order.delivery.title
      .credit_card_info_block
        %h4= t('.payment_info')
        %p #{t('.stars')} #{@order.credit_card.number.last(4)}
        %p #{@order.credit_card.expiration_month}#{t('.slash')}#{@order.credit_card.expiration_year}
    .order_items_confirm
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @order.order_items.each do |order_item|
        .order_item{id: order_item.id}
          %image{src: order_item.book.image, class: "book_ico"}
          .block_title_description
            %h4= order_item.book.title
            %p= order_item.book.description
          .block_info_item
            %h4{class: "book_price"}= number_to_currency(order_item.book.price)
            %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
            %h4{class: "total_book_price"}= number_to_currency(order_item.total_price)
    .order_price_info_confirm
      %h5 #{t('.subtotal')} #{number_to_currency(@order.order_items.sum(:price))}
      %h5 #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5 #{t('.discount')} #{number_to_currency(@order.discount.amount)}
    .order_total_price_info_confirm
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}
    .go_back_store
      = button_to t('.go_store'), books_path, method: :get, class: 'btn btn-primary'

app/views/orders/show.html.haml
.container
  = render "order_items/header"

  .order
    = link_to t('.back_to_orders'), orders_path, class: 'btn btn-default btn-xs'
    .order_title_show
      %h2{class: 'order_number_show'} #{t('.order_number')}#{@order.id}
      %p{class: 'order_state_show'} #{@order.state.tr('_', ' ')}
    .order_items_confirm
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @order.order_items.each do |order_item|
        .order_item{id: order_item.id}
          %image{src: order_item.book.image, class: "book_ico"}
          .block_title_description
            %h4= order_item.book.title
            %p= order_item.book.description
          .block_info_item
            %h4{class: "book_price"}= number_to_currency(order_item.book.price)
            %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
            %h4{class: "total_book_price"}= number_to_currency(order_item.price)
    .order_price_info_confirm
      %h5 #{t('.subtotal')} #{number_to_currency(@order.order_items.sum(:price))}
      %h5 #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5 #{t('.discount')} #{number_to_currency(@order.discount.amount)}
    .order_total_price_info_confirm
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}