config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }

  resources :categories,  only: :show
  resources :order_items, except: [:new, :show, :edit]

  resource :customer, only: :edit do
    collection do
      patch :update_address
      patch :update_password
      patch :update_email
    end
  end

  resources :books, only: [:index, :show]  do
    resources :ratings, only: [:new, :create]
  end

  resources :orders, only: [:index, :show] do
    member do
      get    :complete
      patch  :add_discount
    end
    delete :clear_cart, on: :collection
  end

  namespace :checkouts do
    get   :edit_address
    patch :update_address

    get   :choose_delivery
    patch :set_delivery

    get   :confirm_payment
    patch :update_credit_card

    get   :overview
    get   :confirmation
  end

  root 'home#index'
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_customer!
  before_action :current_order

  def edit_address
  end

  def update_address
    if params[:use_billing_address]
      current_user.billing_address.assign_attributes(billing_params)
      current_user.shipping_address.assign_attributes(billing_params)
    else
      current_user.billing_address.assign_attributes(billing_params)
      current_user.shipping_address.assign_attributes(shipping_params)
    end
    current_user.save
    redirect_to checkouts_choose_delivery_path
  end

  def choose_delivery
    @deliveries = Delivery.all
    @delivery = @order.delivery || @deliveries.first
  end

  def set_delivery
    @order.delivery_id = order_params[:delivery_id]
    @order.set_total_price
    redirect_to checkouts_confirm_payment_path
  end

  def confirm_payment
    @credit_card = @order.credit_card
  end

  def update_credit_card
    @order.credit_card.update(credit_card_params)
    redirect_to checkouts_overview_path
  end

  def overview
    @credit_card = @order.credit_card
    @billing_address = current_user.billing_address
    @shipping_address = current_user.shipping_address
  end

  def confirmation
    @order.confirm(current_user)
    cookies.delete(:order_id)
    redirect_to complete_order_path(@order.id)
  end

  private
  def billing_params
    params.require(:customer).require(:billing_address_attributes).permit(:firstname, :lastname, :street_address, :city, :country, :zipcode, :phone)
  end

  def shipping_params
    params.require(:customer).require(:shipping_address_attributes).permit(:firstname, :lastname, :street_address, :city, :country, :zipcode, :phone)
  end

  def order_params
    params.require(:order).permit(:delivery_id)
  end

  def credit_card_params
    params.require(:credit_card).permit(:number, :expiration_month, :expiration_year, :cvv)
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_payment_header.html.haml
.header
  %h1{class: "project_name"}= t('.title_shop')
  .home
    = link_to t('.home'), root_path, class: 'link_to_home btn btn-primary'
    = link_to t('.shop'), books_path, class: 'btn btn-primary'
  .cart
    %image{src: '/assets/shopping_cart.png'}
    = link_to "#{t('.cart')}(#{@order.items_quantity}) #{number_to_currency(@order.items_price)}", order_items_path
  .user_tools
    = link_to t('.settings'), edit_customer_path, class: 'link_to_settings btn btn-primary'
    = link_to t('.sign_out'), destroy_customer_session_path, method: :delete, class: 'btn btn-primary'

app/views/checkouts/choose_delivery.html.haml
.container
  = render "home/header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'}= t('.checkout')
      = link_to t('.address'), checkouts_edit_address_path, class: 'link_address_title'
      %h4{class: 'delivery_title'}= t('.delivery')
      %h4{class: 'payment_title'}= t('.payment')
      %h4{class: 'confirm_title'}= t('.confirm')
      %h4{class: 'complete_title'}= t('.complete')
    .order_price_column
      %h4{class: 'billing_address'}= t('.bill_addr')
      %h4{class: 'shipping_address'}= t('.shipp_addr')
      %h4{class: 'order_summary'}= t('.order_summary')
    = form_for @order, url: checkouts_set_delivery_path, method: :patch, html: { class: 'select_delivery'} do |f|
      - @deliveries.each do |delivery|
        .delivery
          = f.radio_button :delivery_id, delivery.id, :checked => (delivery == @order.delivery || delivery == @deliveries.first)
          = f.label :delivery_id, "#{delivery.title} #{t('.plus')} #{number_to_currency(delivery.price)}"
      = f.submit t('.submit'), class: 'delivery_submit_form btn btn-primary'
    .order_summary_info_delivery
      %h5{class: 'sum_order_items'} #{t('.item_total_price')} #{number_to_currency(@order.items_price)}
      %h5{class: 'delivery_price_info'} #{t('.shipping_price')} #{number_to_currency(@delivery.price)}
      - if @order.discount
        %h5{class: 'discount_deliveries'} #{t('.discount')} #{number_to_currency(@order.discount.amount)}
      %h5{class: 'order_total_price'} #{t('.order_total_price')} #{number_to_currency(@order.items_price)}

app/views/checkouts/confirm_payment.html.haml
.container
  = render "payment_header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'}= t('.checkout')
      = link_to t('.address'), checkouts_edit_address_path, class: 'link_address_title'
      = link_to t('.delivery'), checkouts_choose_delivery_path, class: 'link_address_title'
      %h4{class: 'payment_title'}= t('.payment')
      %h4{class: 'confirm_title'}= t('.confirm')
      %h4{class: 'complete_title'}= t('.complete')
    .order_price_column
      %h4{class: 'credit_card_column'}= t('.credit_card')
      %h4{class: 'shipping_address'}= t('.shipp_addr')
      %h4{class: 'order_summary_credit_card'}= t('.order_summary')
    = simple_form_for @credit_card, url: checkouts_update_credit_card_path, method: :patch, html: { autocomplete: 'off' } do |f|
      = f.input :number, label: false, placeholder: 'Card Number', input_html: {class: 'input_form', minlength: 16, maxlength: 16}
      = f.label "#{t('.exp_date')}:"
      .expiration_date
        = select_month(Date.today, use_month_numbers: true, prefix: 'credit_card', field_name: 'expiration_month')
        = select_year(Date.today, start_year: 2016, end_year: 2100, prefix: 'credit_card', field_name: 'expiration_year')
      .credit_card
        = f.input :cvv, label: false, placeholder: 'Card Code', input_html: {class: 'input_form_card_code', minlength: 3, maxlength: 3}
        = link_to t('.whats_cvv'), t('.whats_cvv_link'), target: '_blank', class: 'link_credit_card_info'
      = f.submit t('.submit'), class: 'btn btn-primary'
    .order_summary_info_credit_card
      %h5 #{t('.item_total')} #{number_to_currency(@order.items_price)}
      %h5{class: 'delivery_price'} #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5{class: 'discount_cc'} #{t('.discount')} #{number_to_currency(@order.discount.amount)}
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}

app/views/checkouts/edit_address.html.haml
.container
  = render "home/header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'}= t('.checkout')
      %h4{class: 'address_title'}= t('.address')
      %h4{class: 'delivery_title'}= t('.delivery')
      %h4{class: 'payment_title'}= t('.payment')
      %h4{class: 'confirm_title'}= t('.confirm')
      %h4{class: 'complete_title'}= t('.complete')
    .address_and_order_price_columns
      %h4{class: 'billing_address'}= t('.billing_address')
      %h4{class: 'shipping_address'}= t('.shipping_address')
      %h4{class: 'order_summary'}= t('.order_summary')
    = simple_form_for current_user, url: checkouts_update_address_path, method: :patch, html: { class: 'update_address_form' } do |m|
      .billing_address_form
        = m.simple_fields_for :billing_address do |f|
          = f.input :firstname, label: false, placeholder: 'First name', input_html: {class: 'input_form'}
          = f.input :lastname, label: false, placeholder: 'Last name', input_html: {class: 'input_form'}
          = f.input :street_address, label: false, placeholder: 'Street address', input_html: {class: 'input_form'}
          = f.input :city, label: false, placeholder: 'City', input_html: {class: 'input_form'}
          = f.country_select("country", {selected: "US"}, {class: 'input_form'})
          = f.input :zipcode, label: false, as: :integer, placeholder: 'Zipcode', input_html: {class: 'input_form'}
          = f.input :phone, label: false, as: :integer, placeholder: 'Phone number', input_html: {class: 'input_form'}
          = m.submit t('.submit'), class: 'btn btn-primary'
      .block_shipping_form
        .shipping_address_form
          = m.simple_fields_for :shipping_address do |f|
            = f.text_field :firstname, placeholder: 'First name', class: 'input_form'
            = f.text_field :lastname, placeholder: 'Last name', class: 'input_form'
            = f.text_field :street_address, placeholder: 'Street address', class: 'input_form'
            = f.text_field :city, placeholder: 'City', class: 'input_form'
            = f.country_select("country", { include_blank: 'Country' }, {class: 'input_form'})
            = f.number_field :zipcode, placeholder: 'Zipcode', class: 'input_form'
            = f.number_field :phone, placeholder: 'Phone number', class: 'input_form'
        .show_shipping_address_form
          = check_box_tag 'use_billing_address', true, true, class: 'checkbox_use_billing'
          %p= t('.use_bill_addr')
    .order_summary_info
      %h5 #{t('.item_total')} #{number_to_currency(@order.items_price)}
      - if @order.discount
        %h5{class: 'discount'} #{t('.discount')} #{number_to_currency(@order.discount.amount)}
      %h5 #{t('.order_total')} #{number_to_currency(@order.items_price)}

app/views/checkouts/overview.html.haml
.container
  = render "payment_header"

  .address
    .name_columns_checkout
      %h2{class: 'checkout_title'}= t('.checkout')
      = link_to t('.address'), checkouts_edit_address_path, class: 'link_address_title'
      = link_to t('.delivery'), checkouts_choose_delivery_path, class: 'link_address_title'
      = link_to t('.payment'), checkouts_confirm_payment_path, class: 'link_address_title'
      %h4{class: 'confirm_title'}= t('.confirm')
      %h4{class: 'complete_title'}= t('.complete')
    .confirm_block
      %h3= t('.confirm')
      .billing_info_block
        %h4
          #{t('.bill_addr')}
          = link_to t('.edit'), checkouts_edit_address_path
        %p #{@billing_address.firstname} #{@billing_address.lastname}
        %p #{@billing_address.street_address}
        %p #{@billing_address.city} #{@billing_address.zipcode}
        %p #{@billing_address.country}
        %p #{t('.phone')} #{@billing_address.phone}
      .shipping_info_block
        %h4
          #{t('.shipp_addr')}
          = link_to t('.edit'), checkouts_edit_address_path
        %p #{@shipping_address.firstname} #{@shipping_address.lastname}
        %p #{@shipping_address.street_address}
        %p #{@shipping_address.city} #{@shipping_address.zipcode}
        %p #{@shipping_address.country}
        %p #{t('.phone')} #{@shipping_address.phone}
      .delivery_info_block
        %h4
          #{t('.shipments')}
          = link_to t('.edit'), checkouts_choose_delivery_path
        %p #{@order.delivery.title}
      .credit_card_info_block
        %h4
          #{t('.payment_info')}
          = link_to t('.edit'), checkouts_confirm_payment_path
        %p #{t('.stars')} #{@order.credit_card.number.last(4)}
        %p #{@order.credit_card.expiration_month}#{t('.slash')}#{@order.credit_card.expiration_year}
    .order_items_confirm
      .name_columns
        %h5{class: "book_column"}= t('.book')
        %h5{class: "price_column"}= t('.price')
        %h5{class: "qty_column"}= t('.qty')
        %h5{class: "total_column"}= t('.total')
      - @order.order_items.each do |order_item|
        .order_item{id: order_item.id}
          %image{src: order_item.book.image, class: "book_ico"}
          .block_title_description
            %h4= order_item.book.title
            %p= order_item.book.description
          .block_info_item
            %h4{class: "book_price"}= number_to_currency(order_item.book.price)
            %h4{class: "order_item_qty_info_confirm"}= order_item.quantity
            %h4{class: "total_book_price"}= number_to_currency(order_item.price)
    .order_price_info_confirm
      %h5{class: 'subtotal_overview'} #{t('.subtotal')} #{number_to_currency(@order.items_price)}
      %h5 #{t('.shipping')} #{number_to_currency(@order.delivery.price)}
      - if @order.discount
        %h5{class: 'discount_overview'} #{t('.discount')} #{number_to_currency(@order.discount.amount)}
    .order_total_price_info_confirm
      %h5 #{t('.order_total')} #{number_to_currency(@order.total_price)}

    = button_to t('.place_order'), checkouts_confirmation_path, method: :get, class: 'place_order btn btn-primary'